openapi: 3.0.0


info:
  title: Libraries API

  description: |
    # Ferrea Libraries
    This microservice serves as the interface for Libraries handling.

  version: "0.1.1"

  contact:
    "name": "Eugenio Grimoldi"
    "url": "https://github.com/Grimoldi/ferrea-ms-libraries"

  license:
    name: MIT licence
    url: https://mit-license.org/


servers:
  - url: https://ferrea.local
    description: Development local server

  - url: http://localhost:8080
    description: Client tests


paths:
  /api/v1/libraries:
    $ref: "paths/libraries.yaml#/Libraries"
  
  /api/v1/libraries/{name}:
    $ref: "paths/libraries.yaml#/Library"

  /_/health:
    $ref: "paths/probes.yaml#/Liveness"

  /_/ready:
    $ref: "paths/probes.yaml#/Readiness"


components:
  schemas:
    Library:
      $ref: "schemas/library.yaml#/Library"

    Probe:
      $ref: "schemas/probe.yaml#/Probe"

    ValidationError:
      $ref: "schemas/validation_error.yaml#/ValidationError"


tags: 
  - name: libraries
    description: library related operations.

  - name: probes
    description: internal probes.