FerreaError:
  type: object
  properties:
    uuid:
      type: string
    code:
      type: string
    title:
      type: string
    message:
      type: string
  required:
    - detail
  additionalProperties: false
